name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker login -u biairmal -p ${{ secrets.ghcr_pat }}
        docker build . --tag ghcr.io/biairmal/spring-boot-demo:latest
        docker push ghcr.io/biairmal/spring-boot-demo:latest
